links/links/config/routes.rb
require 'api_constraints'

Links::Application.routes.draw do
  
  get "pages/tools"
  get "pages/about"
  get "pages/contact"
  get "delicious/authorize" => 'delicious#authorize', :as => 'delicious_authorize'
  get "delicious/import" => 'delicious#import', :as => 'delicious_import'

  resources :groups # TODO: Clean this up.
  get 'groups/members/:id' => 'groups#members', :as => 'group_members'
  get 'groups/pending_members/:id' => 'groups#pending_members', :as => 'group_pending_members'
  get "groups_owned" => 'groups#owned_groups', :as => 'owned_groups'
  get "groups_invites" => 'groups#group_invites', :as => 'group_invites'
  post "groups/:id/invite_users" => 'groups#invite_users', :as => 'invite_users_to_group'
  put "groups/:group_id/accept_invite/:user_id" => 'groups#accept_invite', :as => 'accept_invite_to_group'
  delete "groups/:group_id/user/:user_id" => 'groups#remove_user', :as => 'remove_user_from_group'
  post "groups/:id/unsubscribe" => 'groups#unsubscribe', :as => 'unsubscribe_user_from_group'
  delete "groups/:group_id/user/:user_id/cancel" => 'groups#cancel_invite', :as => 'cancel_invite_to_user_from_group'
  
  get "searches/index" => "searches#index", :as => 'search_index'
  get "searches/searchmore" => "searches#searchmore", :as => 'search_more'
  
  post "searches/search_user" => "searches#search_user", :as => 'search_user'
  get "searches/search_bookmark" => "searches#search_bookmark", :as => 'search_bookmark'

  use_doorkeeper

	namespace :api,defaults: {format: 'json'} do
			scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do	
          post "/savebookmark"	=> "bookmarks#savebookmark", :as => 'api_savebookmark'
          post "/updatebookmark"  => "bookmarks#updatebookmark", :as => 'api_updatebookmark'
          post "/sharebookmark"  => "bookmarks#share_bookmark_to_groups", :as => 'api_share_bookmark_to_groups'
          get "/timeline" => "bookmarks#timeline", :as => 'api_timeline'
          get "/loadmore/:time" => "bookmarks#loadmore", :as => 'api_loadmore'
          delete "/deletebookmark/:id"  => "bookmarks#deletebookmark", :as => 'api_deletebookmark'      
			end

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do          
          get "/searches/search_bookmark/:keyword" => "searches#search_bookmark", :as => 'api_search_bookmark'
          get "/searches/searchmore/:keyword/:time" => "searches#searchmore", :as => 'api_search_more'
          get "/searches/groups/:id/search_bookmark/:keyword" => "searches#search_bookmark_in_groups", :as => 'api_groups_search_bookmark'
          get "/searches/groups/:id/searchmore/:keyword/:time" => "searches#searchmore_in_groups", :as => 'api_groups_search_more'
      end

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do 
          post "/groups/savebookmark"  => "groups#savebookmark", :as => 'api_groups_savebookmark'         
          get "/groups/index" => "groups#index", :as => 'api_groups'
          get "/groups/requests" => "groups#requests", :as => 'api_groups_requests'
          put "/groups/accept/:group_id" => 'groups#accept_invite', :as => 'api_accept_invite_to_group'
          delete "/groups/reject/:group_id" => 'groups#reject_invite', :as => 'api_reject_invite_to_group'
          delete "/groups/unsubscribe/:group_id" => 'groups#unsubscribe', :as => 'api_unsubscribe_user_from_group'   

          get "/groups/:id/timeline" => "groups#timeline", :as => 'api_groups_timeline'  
          get "/groups/:id/loadmore/:time" => "groups#loadmore", :as => 'api_groups_loadmore'  
      end
	end

  resources :bookmarks
  get "/timeline" => "bookmarks#timeline", :as => 'timeline'
  get "/loadmore" => "bookmarks#loadmore", :as => 'loadmore'
  get 'icon/:id' => 'bookmarks#show_image', :as => 'icon'
  
  get ":id/editbookmark" => "bookmarks#editbookmark", :as => 'editbookmark'
  post "/saveurl" => "bookmarks#saveurl", :as => 'saveurl'
  post "/saveurl/:id" => "bookmarks#saveurl", :as => 'saveurl_for_group_share' 
  post "/savebookmark" => "bookmarks#savebookmark", :as => 'savebookmark'
  post "/savebookmark/:id" => "bookmarks#savebookmark", :as => 'savebookmark_for_group_share'
  post "/updatebookmark" => "bookmarks#updatebookmark", :as => 'updatebookmark'
  post 'bookmarklet' => 'bookmarks#bookmarklet', :as => 'bookmarklet'

  get "/shareable_groups/:bookmark_id" => "groups#shareable_groups", :as => 'shareable_groups'
  post "/sharebookmark" => "bookmarks#share_bookmark_to_groups", :as => 'share_bookmark_to_groups'

  devise_for :users
  get 'users/:id' => 'users#show', :as => 'show_user'

  root to: 'bookmarks#timeline'

  mount Share::Engine, :at => "/share"
  mount Ad::Engine, :at => "/ad"

end

links/links/app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id' #owner
  has_many :memberships
  has_many :users, :through => :memberships #members
  has_many :bookmarks
  validates :name, presence: true
  validates :description, presence: true
end

links/links/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true

	has_many :bookmarks
	has_many :groups # owner relationship
	has_many :memberships
	has_many :groups, :through => :memberships # membership relationship
	
	mount_uploader :image, ImageUploader

end

links/links/app/controllers/api/v1/groups_controller.rb
module Api 
	module V1		
		# Controller for handling all operations related to Groups via REST API
		class GroupsController < ApplicationController
			include GroupsHelper
			doorkeeper_for :all
			skip_before_action :verify_authenticity_token
			respond_to :json

			# Loads the groups
			# This is paginated
			def timeline
				group_bookmarks_loader(Time.now, params[:id]) 
				bookmarks_formatter				
			end
			
			# Loads more groups
			# This is paginated
			def loadmore
				time = Time.at(params[:time].to_i).to_datetime
				group_bookmarks_loader(time, params[:id]) 
				bookmarks_formatter
			end

			# Loads all the groups
			def index
			    all_groups = Group.joins(:users).where("memberships.user_id = ? and memberships.acceptance_status = ?" , doorkeeper_token.resource_owner_id, true)
			    groups_formatter(all_groups)
			end		
			# Loads all the group requests
			def requests
			    invites = Group.joins(:users).where("memberships.user_id = ? and memberships.acceptance_status = ?" , doorkeeper_token.resource_owner_id, false) 
			    groups_formatter(invites)
			end

			# Accepts the invite to a group
			def accept_invite			    			    
			    membership = Membership.find_by_group_id_and_user_id(params[:group_id], doorkeeper_token.resource_owner_id)
			    unless membership.nil?
			      membership.update_attributes :acceptance_status => true
			      respond_to do |format|			        
			        format.json { head :no_content }
			      end
			    else
			      respond_to do |format|			        
			        format.json { render json: "You have not been invited to the group", status: :forbidden}
			      end
			    end
			end
			
			# Rejects the invite to a group
			def reject_invite						    			   
			    membership = Membership.find_by_group_id_and_user_id(params[:group_id], doorkeeper_token.resource_owner_id)
			    unless membership.nil?
			      membership.destroy
			      respond_to do |format|			        
			        format.json { head :no_content }
			      end
			    else
			      respond_to do |format|			        
			        format.json { render json: "You have not been invited to the group", status: :forbidden}
			      end
			    end				
			end

			# Unsubscribe the subscription to a group
			def unsubscribe
				group_id = params[:group_id]
			    if ((!group_owner? doorkeeper_token.resource_owner_id, group_id) && (group_member? doorkeeper_token.resource_owner_id, group_id))
			      set_group(group_id)
			      user = User.find_by_id(doorkeeper_token.resource_owner_id)
			      user.groups.delete(@group)
			      respond_to do |format|			        
			        format.json { head :no_content }
			      end
			    else
			      respond_to do |format|			        
			        format.json { render json: "Only members of a group can unsubscribe from the group. The group owner cannot subscribe from the group", status: :method_not_allowed }
			      end
			    end
   		    end

			# Saves a bookmark in a group as follows:
			# * Saves the URL if not present
			# * Saves the bookmark object
			# * Finds the Tags, if not present, will save the object
			# * Will associate the bookmark with the Group and saves it
			# Handles Async requsts
   		    def savebookmark
			    url_str = save_bookmark_params[:url]
				annotations = get_annotations(url_str)
				url = Url.find_by_url(url_str)
			    if url.nil?
			      url = Url.new({:url => save_bookmark_params[:url], :icon => annotations[:icon]})
			      if !url.save
			        render :status => 404
			      end
			    else
			        Url.update(url.id, :icon => annotations[:icon]) if url.icon.nil? && annotations[:icon] != ''
			    end
			    group_ids = save_bookmark_params['group_ids']
			    @bookmarks = Array.new

			    group_ids.each do |group_id|		    
				    @bookmark = Bookmark.new({:title => save_bookmark_params[:title], :description => save_bookmark_params[:description], :url => url, :user_id => doorkeeper_token.resource_owner_id, :group_id => group_id})			    

				    tags = save_bookmark_params[:tags].split(",")
				    tags.each do |tag|
				      if Tag.where(:tagname => tag.strip.gsub(' ', '-').downcase).size == 0
				        @tag = Tag.new
				        @tag.tagname = tag.strip.gsub(' ','-').downcase
				      @bookmark.tags << @tag
				      else
				        @bookmark.tags << Tag.where(:tagname => tag.strip.gsub(' ', '-').downcase).first
				      end
				    end unless tags.nil?			    
				    
				    if @bookmark.save
				    	@bookmarks << @bookmark
				    else
				       format.json { render json: @bookmark.errors, status: :unprocessable_entity }
				    end	
				end	
				head :ok
			end

			private

			# Util to get bookmark params
			def save_bookmark_params
			    params.permit(:url, :title, :description, :tags, :group_ids => [])
			end

			# Converts Groups to JSON
			def groups_formatter(groups)
				formatted_groups = []
				groups.each do  |group|				  				  
				  formatted_groups << {:id => group.id, :name => group.name, :description => (group.description != nil) ? group.description : ""}
				end
				respond_with formatted_groups
			end			

			# Formats the bookmarks into a JSON
			def bookmarks_formatter
				formatted_bookmarks = []
				@bookmarks.each do  |bookmark|
					formatted_bookmarks << strip_bookmark_to_json(bookmark)
				end
				respond_with formatted_bookmarks
			end

			# Strips the unwanted data off the bookmarks object
			# Params:
			# +bookmark+:: The bookmark object from ActiveModel
			def strip_bookmark_to_json(bookmark)
				formatted_tags = []
				bookmark.tags.each do |tag|
				   formatted_tags << tag.tagname
				end			  				
				bookmark_json = {:id => bookmark.id, :url => bookmark.url.url, :title => bookmark.title, :description => bookmark.description, :updated_at => bookmark.updated_at.to_i, :tags => formatted_tags}

				if bookmark.group_id
					bookmark_json[:username] = bookmark.user.name
					bookmark_json[:groupname] = bookmark.group.name	
				end
				
				if bookmark.user_id == doorkeeper_token.resource_owner_id
					bookmark_json[:my_bookmark] = true
				else
					bookmark_json[:my_bookmark] = false
				end			
				bookmark_json
			end

			# Identifies if the user is group owner or not
			# Params:
			# +user_id+:: User id to be checked
			# +group_id+:: Group id to be checked
			def group_owner?(user_id, group_id)
			    return !Group.where("owner_id = ? and id = ?", user_id, group_id).empty?
			end

			# Loads group object based on group id
			# Params:
			# +group_id+:: ID of group that has to be loaded
			def set_group(group_id)
			    begin
			      @group = Group.find(group_id)
			    rescue ActiveRecord::RecordNotFound
			      #render :file => "public/404.html", :status => :unauthorized, :layout => false
			      redirect_to groups_path, alert: "Specified group, #{group_id}, does not exist"
			    end
			end

			# Identifies if the user is group member or not
			# Params:
			# +user_id+:: User id to be checked
			# +group_id+:: Group id to be checked
			def group_member?(user_id, group_id)
			    return !Membership.where("user_id = ? and group_id = ? and acceptance_status = ?", user_id, group_id, true).empty?
			end

		end
	end
end

links/links/app/helpers/groups_helper.rb
module GroupsHelper
	def group_bookmarks_loader(time, group_id)			    
	    @bookmarks = Bookmark.eager_load(:tags, :user, :url)
	      .eager_load(group: :memberships)
      	  .where("bookmarks.group_id = ?", group_id)	      
	      .where("bookmarks.updated_at < :now", now: time)
	      .order('bookmarks.updated_at DESC')
	      .limit(20)
  	end
end

links/links/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

links/links/app/views/groups/_group_select.html.erb
<div class="bookmark-share-form">
  <div class="bookmark-share-form-title">
  	<h3>Share Bookmark</h3>
  </div>
  <%= form_tag("/sharebookmark", method: "post", remote: true) do %>  
  		<%= hidden_field_tag(:bookmark_id, @bookmark_id) %>
      	<div>      				  
		  <% @all_groups.each do |group| %>
		    <div class="checkbox">
			  <label>
			    <%= check_box_tag 'group_ids[]', group.id %>
		        <%= h group.name %>
			  </label>
			</div>
		  <% end %>			
      	</div>
      	<div class="bookmark-share-form-actions">
  			<%= button_tag("Cancel", class:"btn", type:"button", id:"cancel_share_bookmark") %>		
  			<%= submit_tag("Share", class:"btn") %>
		</div>		
  <% end %>
</div>

links/links/app/views/groups/_groups.html.erb
<%= content_for :center do %>
<div id='groups-content'>
	<%= render_navigation(:level => 1) %>
	<div id='filler'>&nbsp;</div>
	<%= render_navigation(:level => 2) %>
</div>
<% end %>

links/links/app/views/groups/edit.html.erb
<%= content_for :center do%>
<div id='groups-content'>
<%= render_navigation :level => 1%>
<div id='filler'>
	&nbsp;
</div>

<h4>Editing group</h4>

<%= form_for(@group, :method => :patch) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<% end %>

links/links/app/views/groups/group_invites.html.erb
<%= content_for :center do %>
<div id='groups-content'>
	<%= render_navigation(:level => 1) %>
	<div id='filler'>&nbsp;</div>

	<div id='filler'>
		&nbsp;
	</div>

	<ul class='subgroups-nav'>
		<% @invites.each do |group| %>
		<li>
			<%= link_to group.name, accept_invite_to_group_path(group, current_user), method: :put %>
			<div class='action'>
			<%= link_to 'Accept', accept_invite_to_group_path(group, current_user), {:method => :put, :class => 'btn'} %>
			</div>
			
		</li>
		<% end unless @invites.nil?%>
	</ul>
</div>
<% end %>

links/links/app/views/groups/index.html.erb
<%= content_for :center do %>
<div id='groups-content'>
	<%= render_navigation(:level => 1) %>
	<div id='filler'>&nbsp;</div>

	<div id='filler'>
		&nbsp;
	</div>

	<ul class='subgroups-nav'>
		<% @all_groups.each do |group| %>
		<li>
			<%= link_to group.name, group_path(group) %>
			<% if GroupsController.group_owner? current_user.id, group.id %>
			<div class='action'>
			<%= link_to 'Edit', edit_group_path(group), {:class => 'btn'} %>
			<%= link_to 'Delete', group_path(group), {:method => :delete , :class => 'btn'}%>
			</div>
			<% else %>
			<div class='action'>
			<%= link_to 'Unsubscribe', unsubscribe_user_from_group_path(group), :method => :post, :class => 'btn' %>
			</div>
			<% end %>
			
		</li>
		<% end unless @all_groups.nil?%>
	</ul>
</div>
<% end %>

links/links/app/views/groups/members.html.erb
<%= content_for :center do %>
<div id='groups-content'>
	<%= render_navigation :context => :group_menu%>

	<div id='filler'>
		&nbsp;
	</div>

	<ul class='subgroups-nav'>
		<% @members.each do |user| %>
		<li>
				<%= link_to user.name, show_user_path(user) %> 
				<% if GroupsController.group_owner?(current_user.id, @group.id) && !GroupsController.group_owner?(user.id, @group.id) %>
				<div class='action'>
					<%= link_to 'Remove', remove_user_from_group_path(@group, user), method: :delete, :class => 'btn', data: { confirm: 'Are you sure?' } %>
				</div> 
				<% end %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

links/links/app/views/groups/new.html.erb
<%= content_for :center do%>
<div id='groups-content'>
<%= render_navigation :level => 1%>
<div id='filler'>
	&nbsp;
</div>
<h4>Create New Group</h4>
<%= render 'form' %>
</div>
<% end %>

links/links/app/views/groups/owned_groups.html.erb
<%= content_for :center do %>
<div id='groups-content'>
	<%= render_navigation(:level => 1) %>
	<div id='filler'>&nbsp;</div>

	<div id='filler'>
		&nbsp;
	</div>

	<ul class='subgroups-nav'>
		<% @owned_groups.each do |group| %>
		<li>
			<%= link_to group.name, group_path(group) %>
			<% if GroupsController.group_owner? current_user.id, group.id %>
			<div class='action'>
			<%= link_to 'Edit', edit_group_path(group), {:class => 'btn'} %>
			<%= link_to 'Delete', group_path(group), {:method => :delete, :class => 'btn'} %>
			</div>
			<% end %>
			
		</li>
		<% end unless @owned_groups.nil?%>
	</ul>
</div>
<% end %>

links/links/app/views/groups/pending_members.html.erb
<%= content_for :center do%>
<div id='groups-content'>
	<%= render_navigation :context => :group_menu%>

	<div id='filler'>
		&nbsp;
	</div>

	<ul class='subgroups-nav'>
		<% @pending_members.each do |user| %>
		<li>
			<span>
			<%= link_to user.name, show_user_path(user)%>
							<% if GroupsController.group_owner?(current_user.id, @group.id) && !GroupsController.group_owner?(user.id, @group.id) %>
			<div class='right'>
				<%= link_to 'Cancel', cancel_invite_to_user_from_group_path(@group, user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
			</div>
			<% end %>
			</span>
		</li>
		<% end unless @pending_members.nil?%>
	</ul>
</div>
<% end %>

links/links/app/views/groups/shareable_groups.js.erb
$('#overlay').removeClass("overlay-invisible").addClass("overlay-visible");
$('#overlay').html('<%= escape_javascript("#{render(:partial => 'group_select')}").html_safe %>');

links/links/app/views/groups/show.html.erb
<%= content_for :center do%>
<div id='groups-content'>
	<%= render_navigation :context => :group_menu%>
	<div id='filler'>
		&nbsp;
	</div>

	<div id='content'>
		<div id='details'>
			<div id='group-owner'>
				<strong>Group Owner:</strong>
				<%= link_to @group.owner.name, show_user_path(@group.owner)%>
			</div>
			<div id='filler'>
				&nbsp;
			</div>
			<div id='group-description'>
				<%= @group.description %>
			</div>
		</div>
		<% if GroupsController.group_owner? current_user.id, @group.id %>
		<div id='filler'>
			&nbsp;
		</div>
		<div id='add-users'>
			<%= form_tag(invite_users_to_group_path(@group), method: "post", :id => "form") do %>
			<div id="magicsuggest"></div>
			<input type="text" name="users[]" id="ms" placeholder="Add Users">
			</input>
			<%= submit_tag "Invite", :id => "submit", :class => 'btn' %>
			<%end %>
		</div>
		<% end %>
		&nbsp;
	</div>

	<div id='filler'>
		&nbsp;
	</div>

	<div class="timeline">
		<div id='share'>
			<h4>Shares</h4>
			<%= form_tag(saveurl_for_group_share_path(@group), method: "post", remote: true) do %>
			<%= text_field_tag(:url, nil, {placeholder: "Paste the URL here..."}) %>
			<%= submit_tag("Share", class:'btn') %>
			<% end %>
		</div>

		<div class="links">
			<%= render(:partial => "bookmarks/user_links") %>
		</div>

	</div>
</div>
<%= javascript_include_tag "searches", "data-turbolinks-track" => true %>
<% end %>