prototype_0_1/config/routes.rb
Links::Application.routes.draw do

  get "welcome/index"
  root to: "welcome#index"
  
  get "sessions/login" 
  post "login_attempt", to: "sessions#login_attempt" 
  get "logout", to: "sessions#logout"
  
  resources :users
  get '/links/new', to: 'links#new' , :as => 'my_new_link' 
  post '/links/', to: 'links#create', :as => 'create_my_link'
  get '/links/:id/edit(.:format)', to: 'links#edit', :as => 'edit_link'
  get '/links', to: 'links#index', :as => 'my_links'
  get '/links/:id', to: 'links#show'  
  patch '/links/:id', to: 'links#update'
  put '/links/:id', to: 'links#update'
  delete '/links/:id', to: 'links#destroy', :as => 'delete_link'

end

prototype_0_1/app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
end

prototype_0_1/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :links
end

prototype_0_1/app/models/user.rb
class User < ActiveRecord::Base
	has_many :links
	EMAIL_REGEX = "^.+@.+$"
	def self.authenticate(username_or_email="", login_password="")		
		if  EMAIL_REGEX.match(username_or_email)    
			user = User.find_by_email(username_or_email)
		else
			user = User.find_by_username(username_or_email)
		end
		if user && user.match_password(login_password)
			return user
		else
			return false
		end
	end   
	def match_password(login_password="")
		password == login_password
	end
		
end

prototype_0_1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 
  def authenticate_user
  		if session[:user_id]
     # set current user object to @current_user object variable
     		@current_user = User.find session[:user_id] 
     		return true	
 		else
 			redirect_to(:controller => 'sessions', :action => 'login')
 			return false
 		end
  	end

	def save_login_state
		if session[:user_id]
			redirect_to(:controller => 'links', :action => 'index')
			return false
		else
			return true
		end
	end

end

prototype_0_1/app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :authenticate_user, :only => [:show, :index, :new, :create, :edit, :update, :destroy]	
  def show  	
  	@link = Link.find(params[:id])
  end

  def index
  	@links = @current_user.links
  end

  def new
    @link = Link.new
  end

  def create
	link = link_params
	tags = link.delete("tags").split(","); # TODO: fix this
    @link = Link.new(link)
  	tags.each do |tag|
  			if Tag.where(:tagName => tag.strip.gsub(' ', '-').downcase).size == 0
  				@tag = Tag.new
  				@tag.tagName = tag.strip.gsub(' ','-').downcase 
  				@link.tags << @tag
  			else
  				@link.tags << Tag.where(:tagName => tag.strip.gsub(' ', '-').downcase).first
  			end
  	end
    @current_user.links << @link
    respond_to do |format|
      if @link.save
        format.html { redirect_to :url=>{:action=>'index'}, notice: 'Link was successfully created.' }        
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = link_params
    tags = link.delete("tags").split(","); # TODO: fix this
    @link = Link.find(params[:id])
    @link.tags.clear
    tags.each do |tag|
        if Tag.where(:tagName => tag.strip.gsub(' ', '-').downcase).size == 0
          @tag = Tag.new
          @tag.tagName = tag.strip.gsub(' ','-').downcase 
          @link.tags << @tag
        else
          @link.tags << Tag.where(:tagName => tag.strip.gsub(' ', '-').downcase).first
        end
    end    
    respond_to do |format|
      if @link.update(link)
        format.html { redirect_to :url=>{:action=>'index'}, notice: 'Link was successfully updated.' }        
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    respond_to do |format|
      format.html { redirect_to my_links_url }      
    end
  end

  def link_params
      params.require(:link).permit(:url, :title, :description, :tags)
  end
end

prototype_0_1/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController	
	before_filter :save_login_state, :only => [:login, :login_attempt]
	def login
	end

	def logout
  		session[:user_id] = nil
  		redirect_to :action => 'login'
	end
	
	def login_attempt
		authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
		if authorized_user
			session[:user_id] = authorized_user.id
			flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.username}"
			redirect_to url_for(:controller => 'links', :action => 'index')
		else
			flash[:notice] = "Invalid Username or Password"
			flash[:color]= "invalid"
			render "login"	
		end
	end
end

prototype_0_1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :firstname, :lastname, :email)
    end
end

prototype_0_1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :save_login_state, :only => [:index]
  def index
  	if params[:username_or_email]
	  	authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
	  	if authorized_user
				session[:user_id] = authorized_user.id	
				redirect_to url_for(:controller => 'links', :action => 'index')
		end
	end
  end
end

prototype_0_1/app/helpers/links_helper.rb
module LinksHelper
end

prototype_0_1/app/helpers/sessions_helper.rb
module SessionsHelper
end

prototype_0_1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

prototype_0_1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <!-- Everything in here gets hidden at 940px or less -->
	      <a class="brand" href="/sessions/login">
          	Links	
       	  </a>
	      <div class="nav-collapse">
	        <!-- menu items gets rendered here instead -->
	      </div>
	    </div>
	  </div>
	</div>
	<div class="container">
		<div class="row">
			<div class="span9"><%= yield %></div>
			<div class="span3">
				<h1>About Us</h1>
				Traditional bookmarking services do not allow storing information on private servers. The application should allow deploying a local server which is capable of the following for every user/client:
				<ul>
					<li>Bookmarking URLs</li>
					<li>Tagging the URLs</li>
					<li>Searching among the links</li>
					<li>Annotations for a given URL</li>
					<li>Multi-user</li>
					<li>Expose an API</li>
				</ul>
			</div>			
		</div>		
	</div>
</body>
</html>

prototype_0_1/app/views/links/edit.html.erb
<%= form_for(@link,:url=>{:action=>'update'}) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this Link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="control-group">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="control-group">
      <%= f.label :tags %><br>
      <% tags = "" %>
        <% @link.tags.each do |tag| %> 
          <% tags << tag.tagName + ", " %>
        <%  end %>         
	    <%= f.text_field :tags, :value => tags.chomp(", ") %>   <%# TODO: fix this -%>
    </div>
    <div class="form-actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

<%= link_to 'Back', url_for(:controller => 'links', :action => 'index') %>

prototype_0_1/app/views/links/index.html.erb
<html>
<head>
	<title>All My Links</title> </head>
	<%= link_to 'Logout', url_for(:controller => 'sessions', :action => 'logout') %>
	<body>
		<h1>All My Links</h1> 
		<ul>
			<% for link in @links %>
				<li>
					<a href="/links/<%= link.id %>"><%= link.title %></a>
				</li> 
			<% end %>
		</ul>
		<%= link_to 'Add New Link', url_for(:controller => 'links', :action => 'new') %>
	</body>
</html>

prototype_0_1/app/views/links/new.html.erb
<%= form_for(@link,:url=>{:action=>'create'}) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this Link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="control-group">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="control-group">
      <%= f.label :tags %><br>
	  <%= f.text_field :tags, :value => "" %>   <%# TODO: fix this -%>
    </div>
    <div class="form-actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

<%= link_to 'Back', url_for(:controller => 'links', :action => 'index') %>

prototype_0_1/app/views/links/show.html.erb
<html>
<head>
	<title><%= @link.title %></title> </head>
	<body> 
		<fieldset>
			<div class="control-group">
				<b>Link:</b> <a href="<%= @link.url %>" target="_tab"><%= @link.url %></a>
			</div>
			<div class="control-group">			
				<b>Title:</b> <%= @link.title %>
			</div>
			<div class="control-group">			
				<b>Description:</b> <%= @link.description %> 
			</div>	
			<div class="control-group">			
				<b>Tags: </b> 
				<% tags = "" %>
				<% @link.tags.each do |tag| %> 
					<% tags << tag.tagName + ", " %>
				<%	end	%> 
				<%= tags.chomp(", ") %>
			</div>	
			<div class="form-actions">
				<%= link_to 'Back', my_links_path %>	
				<%= link_to 'Edit', edit_link_path(@link) %>
				<%= link_to 'Delete', url_for(:controller => 'links', :action => 'destroy'), method: :delete %>
			</div>
		</fieldset>
	</body>
</html>