links/links/config/routes.rb
require 'api_constraints'

Links::Application.routes.draw do
  
  get "pages/tools"
  get "pages/about"
  get "pages/contact"
  get "delicious/authorize" => 'delicious#authorize', :as => 'delicious_authorize'
  get "delicious/import" => 'delicious#import', :as => 'delicious_import'

  resources :groups # TODO: Clean this up.
  get 'groups/members/:id' => 'groups#members', :as => 'group_members'
  get 'groups/pending_members/:id' => 'groups#pending_members', :as => 'group_pending_members'
  get "groups_owned" => 'groups#owned_groups', :as => 'owned_groups'
  get "groups_invites" => 'groups#group_invites', :as => 'group_invites'
  post "groups/:id/invite_users" => 'groups#invite_users', :as => 'invite_users_to_group'
  put "groups/:group_id/accept_invite/:user_id" => 'groups#accept_invite', :as => 'accept_invite_to_group'
  delete "groups/:group_id/user/:user_id" => 'groups#remove_user', :as => 'remove_user_from_group'
  post "groups/:id/unsubscribe" => 'groups#unsubscribe', :as => 'unsubscribe_user_from_group'
  delete "groups/:group_id/user/:user_id/cancel" => 'groups#cancel_invite', :as => 'cancel_invite_to_user_from_group'
  
  get "searches/index" => "searches#index", :as => 'search_index'
  get "searches/searchmore" => "searches#searchmore", :as => 'search_more'
  
  post "searches/search_user" => "searches#search_user", :as => 'search_user'
  get "searches/search_bookmark" => "searches#search_bookmark", :as => 'search_bookmark'

  use_doorkeeper

	namespace :api,defaults: {format: 'json'} do
			scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do	
          post "/savebookmark"	=> "bookmarks#savebookmark", :as => 'api_savebookmark'
          post "/updatebookmark"  => "bookmarks#updatebookmark", :as => 'api_updatebookmark'
          post "/sharebookmark"  => "bookmarks#share_bookmark_to_groups", :as => 'api_share_bookmark_to_groups'
          get "/timeline" => "bookmarks#timeline", :as => 'api_timeline'
          get "/loadmore/:time" => "bookmarks#loadmore", :as => 'api_loadmore'
          delete "/deletebookmark/:id"  => "bookmarks#deletebookmark", :as => 'api_deletebookmark'      
			end

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do          
          get "/searches/search_bookmark/:keyword" => "searches#search_bookmark", :as => 'api_search_bookmark'
          get "/searches/searchmore/:keyword/:time" => "searches#searchmore", :as => 'api_search_more'
          get "/searches/groups/:id/search_bookmark/:keyword" => "searches#search_bookmark_in_groups", :as => 'api_groups_search_bookmark'
          get "/searches/groups/:id/searchmore/:keyword/:time" => "searches#searchmore_in_groups", :as => 'api_groups_search_more'
      end

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do 
          post "/groups/savebookmark"  => "groups#savebookmark", :as => 'api_groups_savebookmark'         
          get "/groups/index" => "groups#index", :as => 'api_groups'
          get "/groups/requests" => "groups#requests", :as => 'api_groups_requests'
          put "/groups/accept/:group_id" => 'groups#accept_invite', :as => 'api_accept_invite_to_group'
          delete "/groups/reject/:group_id" => 'groups#reject_invite', :as => 'api_reject_invite_to_group'
          delete "/groups/unsubscribe/:group_id" => 'groups#unsubscribe', :as => 'api_unsubscribe_user_from_group'   

          get "/groups/:id/timeline" => "groups#timeline", :as => 'api_groups_timeline'  
          get "/groups/:id/loadmore/:time" => "groups#loadmore", :as => 'api_groups_loadmore'  
      end
	end

  resources :bookmarks
  get "/timeline" => "bookmarks#timeline", :as => 'timeline'
  get "/loadmore" => "bookmarks#loadmore", :as => 'loadmore'
  get 'icon/:id' => 'bookmarks#show_image', :as => 'icon'
  
  get ":id/editbookmark" => "bookmarks#editbookmark", :as => 'editbookmark'
  post "/saveurl" => "bookmarks#saveurl", :as => 'saveurl'
  post "/saveurl/:id" => "bookmarks#saveurl", :as => 'saveurl_for_group_share' 
  post "/savebookmark" => "bookmarks#savebookmark", :as => 'savebookmark'
  post "/savebookmark/:id" => "bookmarks#savebookmark", :as => 'savebookmark_for_group_share'
  post "/updatebookmark" => "bookmarks#updatebookmark", :as => 'updatebookmark'
  post 'bookmarklet' => 'bookmarks#bookmarklet', :as => 'bookmarklet'

  get "/shareable_groups/:bookmark_id" => "groups#shareable_groups", :as => 'shareable_groups'
  post "/sharebookmark" => "bookmarks#share_bookmark_to_groups", :as => 'share_bookmark_to_groups'

  devise_for :users
  get 'users/:id' => 'users#show', :as => 'show_user'

  root to: 'bookmarks#timeline'

  mount Share::Engine, :at => "/share"
  mount Ad::Engine, :at => "/ad"

end

links/links/app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Links", timeline_path, :class => 'brand'%>
			<div class="nav-collapse">
				<ul class="nav">
				    <li>
				    	<%= link_to "Groups", groups_path %>
			        </li>
   					<li>
						<%= link_to "Tools", '/pages/tools'%>						
					</li>			        
					<li>
  						<%= link_to "Search", timeline_path %>
				    </li>
				</ul>
				<ul class="nav pull-right">
					<li>
			        	<%= link_to "Me", show_user_path(current_user) %>
			        </li>
			        <li>
			        	<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>	
			        </li>   			        
				</ul>
			</div>
		</div>
	</div>
</div>	

links/links/app/views/layouts/_page_plugins.html.erb
<% @page_plugins = PLUGIN_CONFIG['pages'] %>
<% for page_plugin_key in @page_plugins.keys %>
	<%														
		page_plugin =  @page_plugins[page_plugin_key]														
		resource_point = page_plugin['resource_point']							
	%>
	<div>
		<% if page_plugin['enabled'] %>
			<%= render resource_point %>
		<% end %>
	</div>
<% end %>

links/links/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<%= render "layouts/navbar" %>			
	<% end %>

	<div class="container">
		<div class="row">
			<div class="span6">
				<%= yield %>
			</div>
			<div class="span6">
				<h1>Links</h1>
				<h4>A free, open-sourced online bookmarking service.</h4>
				Traditional bookmarking services do not allow storing information on private servers. The application should allow deploying a local server which is capable of the following for every user/client:
				<ul>
					<li>Bookmarking URLs</li>
					<li>Tagging the URLs</li>
					<li>Searching among the links</li>
					<li>Annotations for a given URL</li>					
					<li>Exposes REST APIs</li>
				</ul>
			</div>						
		</div>
		<!--
		<div class="row">
			<% @page_plugins = PLUGIN_CONFIG['pages'] %>
			<% for page_plugin_key in @page_plugins.keys %>
				<%														
					page_plugin =  @page_plugins[page_plugin_key]														
					resource_point = page_plugin['resource_point']							
				%>
				<div>
					<% if page_plugin['enabled'] %>
						<%= render resource_point %>
					<% end %>
				</div>
			<% end %>
		</div>
		-->
	</div>
</body>
</html>

links/links/app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="overlay" class="overlay-invisible">
	</div>
	<% if current_user %>
		<%= render "layouts/navbar" %>
	<% end %>
	<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: name %>
	<% end -%>


	<div class="timeline">
		<div>
	<div class="left-pane">
		<%= render "bookmarks/timeline_form" %>
	</div>
	<div class="right-pane">
		<%= yield %>		
	</div>
	<div class="clear"></div>
</div>				
	</div>
</body>
</html>

links/links/app/views/layouts/bookmarks.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="overlay" class="overlay-invisible">
	</div>
	<% if current_user %>
		<%= render "layouts/navbar" %>
	<% end %>

	<div class="timeline">
		<%= yield %>						
	</div>
</body>
</html>

links/links/app/views/layouts/groups.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Links</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="overlay" class="overlay-invisible"></div>
		<% if current_user %>
		<%= render "layouts/navbar" %>
		<% end %>
		<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
		<% end -%>

		<div id='groups-layout'>
			<div id="groups-layout-left">
				&nbsp;
			</div>
			<div id='groups-layout-center'>
				<%= yield :center %>
			</div>
			<div id='groups-layout-right'>
				&nbsp;
			</div>
		</div>
	</body>
</html>

links/links/app/views/layouts/links.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="overlay" class="overlay-invisible">
	</div>
	<% if current_user %>
		<%= render "layouts/navbar" %>
	<% end %>

	<div class="timeline">
		<%= yield %>						
	</div>
</body>
</html>